export function createBinaryStl(mesh, name = "physicalflare") {
  const triangleCount = mesh.indices.length / 3;
  const buffer = new ArrayBuffer(84 + triangleCount * 50);
  const view = new DataView(buffer);
  const encoder = new TextEncoder();
  const header = encoder.encode(`${name} - generated by physicalflare`);
  new Uint8Array(buffer, 0, Math.min(80, header.length)).set(
    header.slice(0, 80)
  );
  view.setUint32(80, triangleCount, true);

  let offset = 84;
  const a = [0, 0, 0];
  const b = [0, 0, 0];
  const c = [0, 0, 0];

  for (let i = 0; i < mesh.indices.length; i += 3) {
    readVertex(mesh.positions, mesh.indices[i], a);
    readVertex(mesh.positions, mesh.indices[i + 1], b);
    readVertex(mesh.positions, mesh.indices[i + 2], c);
    const normal = calculateNormal(a, b, c);

    offset = writeVector(view, offset, normal);
    offset = writeVector(view, offset, a);
    offset = writeVector(view, offset, b);
    offset = writeVector(view, offset, c);
    view.setUint16(offset, 0, true);
    offset += 2;
  }

  return new Blob([buffer], { type: "model/stl" });
}

export function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  setTimeout(() => URL.revokeObjectURL(url), 500);
}

function readVertex(positions, index, target) {
  const i = index * 3;
  target[0] = positions[i];
  target[1] = positions[i + 1];
  target[2] = positions[i + 2];
}

function calculateNormal(a, b, c) {
  const ab = [b[0] - a[0], b[1] - a[1], b[2] - a[2]];
  const ac = [c[0] - a[0], c[1] - a[1], c[2] - a[2]];
  const normal = [
    ab[1] * ac[2] - ab[2] * ac[1],
    ab[2] * ac[0] - ab[0] * ac[2],
    ab[0] * ac[1] - ab[1] * ac[0]
  ];
  const length = Math.hypot(normal[0], normal[1], normal[2]) || 1;
  return [normal[0] / length, normal[1] / length, normal[2] / length];
}

function writeVector(view, offset, vector) {
  view.setFloat32(offset, vector[0], true);
  view.setFloat32(offset + 4, vector[1], true);
  view.setFloat32(offset + 8, vector[2], true);
  return offset + 12;
}
